"""Beancount output generator."""

from datetime import datetime
from decimal import Decimal
from io import StringIO
from pathlib import Path

from .types import MatchSource, ReconcileResult, Transaction


class BeancountWriter:
    """Generate Beancount format output from transactions."""

    def __init__(
        self,
        default_expense: str = "Expenses:FIXME",
        default_income: str = "Income:FIXME",
    ):
        self.default_expense = default_expense
        self.default_income = default_income

    def format_transaction(self, txn: Transaction) -> str:
        """Format a single transaction as Beancount entry."""
        lines = []

        # Transaction header: date flag "payee" "narration"
        payee_str = f'"{txn.payee}"' if txn.payee else '""'
        narration = txn.description.replace('"', '\\"')
        lines.append(f'{txn.date} {txn.flag} {payee_str} "{narration}"')

        # Metadata
        meta_lines = self._format_metadata(txn)
        for meta in meta_lines:
            lines.append(f"  {meta}")

        # Postings
        postings = self._format_postings(txn)
        for posting in postings:
            lines.append(f"  {posting}")

        return "\n".join(lines)

    def _format_metadata(self, txn: Transaction) -> list[str]:
        """Format transaction metadata."""
        meta = []

        # Standard metadata
        if txn.time:
            meta.append(f'time: "{txn.time.strftime("%H:%M:%S")}"')

        if txn.order_id:
            meta.append(f'order_id: "{txn.order_id}"')

        if txn.metadata.get("reference"):
            meta.append(f'reference: "{txn.metadata["reference"]}"')

        # Match source
        if txn.match_source:
            source_str = txn.match_source.value
            if txn.metadata.get("matched_rule"):
                source_str = f"rule:{txn.metadata['matched_rule']}"
            meta.append(f'source: "{source_str}"')

        # Additional metadata from provider
        skip_keys = {"_ignored", "matched_rule", "reference", "original_payee"}
        for key, value in txn.metadata.items():
            if key in skip_keys:
                continue
            if isinstance(value, str):
                meta.append(f'{key}: "{value}"')
            elif isinstance(value, bool):
                meta.append(f"{key}: {str(value).upper()}")
            elif isinstance(value, (int, float, Decimal)):
                meta.append(f"{key}: {value}")

        return meta

    def _format_postings(self, txn: Transaction) -> list[str]:
        """Format transaction postings."""
        postings = []

        # Primary account (asset/liability)
        account = txn.account or "Assets:FIXME"
        amount = -txn.amount  # Statement shows outflow as positive
        postings.append(f"{account}  {amount} {txn.currency}")

        # Contra account (expense/income)
        contra = txn.contra_account
        if not contra:
            contra = self.default_expense if txn.is_expense else self.default_income
        postings.append(f"{contra}  {txn.amount} {txn.currency}")

        return postings

    def format_transactions(
        self,
        transactions: list[Transaction],
        source_info: str | None = None,
    ) -> str:
        """Format multiple transactions with header."""
        output = StringIO()

        # Header
        output.write("; " + "=" * 60 + "\n")
        output.write("; Generated by Bean-Sieve\n")
        output.write(f"; Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        if source_info:
            output.write(f"; Source: {source_info}\n")
        output.write("; " + "=" * 60 + "\n\n")

        # Group transactions by match source
        fixme_txns = [t for t in transactions if t.match_source == MatchSource.FIXME]
        rule_txns = [t for t in transactions if t.match_source == MatchSource.RULE]
        predict_txns = [
            t for t in transactions if t.match_source == MatchSource.PREDICT
        ]
        unmatched = [t for t in transactions if t.match_source is None]

        # Write each group
        if rule_txns:
            output.write(f"; --- Rule matched ({len(rule_txns)}) ---\n\n")
            for txn in sorted(rule_txns, key=lambda t: t.date):
                output.write(self.format_transaction(txn) + "\n\n")

        if predict_txns:
            output.write(f"; --- ML predicted ({len(predict_txns)}) ---\n\n")
            for txn in sorted(predict_txns, key=lambda t: t.date):
                output.write(self.format_transaction(txn) + "\n\n")

        if fixme_txns or unmatched:
            count = len(fixme_txns) + len(unmatched)
            output.write(f"; --- Needs review ({count}) ---\n\n")
            for txn in sorted(fixme_txns + unmatched, key=lambda t: t.date):
                output.write(self.format_transaction(txn) + "\n\n")

        return output.getvalue()

    def format_result(
        self, result: ReconcileResult, source_info: str | None = None
    ) -> str:
        """Format complete reconcile result."""
        output = StringIO()

        # Main content
        output.write(
            self.format_transactions(result.processed, source_info=source_info)
        )

        # Summary
        output.write("; --- Summary ---\n")
        output.write(f"; {result.match_result.summary}\n")

        # Extra entries (in ledger but not in statement)
        if result.match_result.extra:
            output.write(
                f"; \n; Extra entries in ledger ({len(result.match_result.extra)}):\n"
            )
            for entry in result.match_result.extra[:10]:  # Limit output
                txn = entry.txn
                posting = entry.posting
                amount = posting.units.number if posting.units else "?"
                output.write(f";   - {txn.date} {amount} @ {posting.account}\n")
            if len(result.match_result.extra) > 10:
                output.write(
                    f";   ... and {len(result.match_result.extra) - 10} more\n"
                )

        return output.getvalue()


def write_output(
    result: ReconcileResult,
    output_path: Path,
    source_info: str | None = None,
    default_expense: str = "Expenses:FIXME",
    default_income: str = "Income:FIXME",
) -> None:
    """
    Write reconcile result to Beancount file.

    Convenience function for common usage.
    """
    writer = BeancountWriter(
        default_expense=default_expense,
        default_income=default_income,
    )
    content = writer.format_result(result, source_info=source_info)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)
